const FETCH_MENU_ITEMS_START = 'FETCH_MENU_ITEMS_START'
const FETCH_MENU_ITEMS_SUCCESS = 'FETCH_MENU_ITEMS_SUCCESS'
const FETCH_MENU_ITEMS_ERROR = 'FETCH_MENU_ITEMS_ERROR'


export default {
    FETCH_MENU_ITEMS_START,
    FETCH_MENU_ITEMS_SUCCESS,
    FETCH_MENU_ITEMS_ERROR,
}